# Generated by Django 6.1 on 2026-09-30 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_atividade_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('nota', models.FloatField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subatividades', to='sistema.atividade')),
            ],
        ),
    ]
